catalogMode: prefer

minimumReleaseAgeExclude:
  - bumpp@12.2.1
shellEmulator: true

trustPolicy: no-downgrade

packages: []
allowBuilds:
  esbuild: true
  simple-git-hooks: true
catalogs:
  build:
    tsdown: ^0.23.0
  dev:
    bumpp: ^12.3.0
    pncat: ^0.13.4
    simple-git-hooks: ^2.14.0
    taze: ^21.1.0
    tsx: ^4.23.15
    typescript: ^6.0.3
  lint:
    '@octohash/eslint-config': ^0.5.3
    eslint: ^10.11.0
    lint-staged: ^17.6.0
  prod:
    '@clack/prompts': ^1.8.1
    ansis: ^4.4.0
    cac: ^7.0.0
    ofetch: ^1.5.1
    p-limit: ^7.3.3
    p-retry: ^8.0.1
    pathe: ^2.0.3
  test:
    vitest: 5.0.1
  types:
    '@types/node': ^26.6.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
